// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.ctrlTab.sortByRecentlyUsed", true);
user_pref("browser.fullscreen.exit_on_escape", false);
user_pref("browser.history_swipe_animation.disabled", true);
user_pref("browser.urlbar.trimURLs", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.tabs.loadBookmarksInTabs", true);
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);
